version: '3'

networks:
  akc-net:

services:
  akc-database:
    container_name: akc-database
    image: postgres
    env_file:
      - .env
    volumes:
      - akc-database-data:/var/lib/postgresql/data/
    networks:
      - akc-net
    ports:
      - 5432:5432

volumes:
  akc-database-data:
