version: '3'

services:
  test-db:
    image: mysql:5.5
    container_name: test-db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - .:/test-app
    environment:
      # Các thông số này thay đổi theo password mysql trên máy bạn nhé.
      MYSQL_ROOT_PASSWORD: password #
      MYSQL_DATABASE: testdb
      MYSQL_USER: user_testdb
      MYSQL_PASSWORD: password

# Tạo volume để lần sau có build lại cũng nhanh hơn
volumes:
  db_data:
  web_rubygems:
